apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: iot-sad-zvuk
  labels:
    app: mosquitto
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous false
    password_file /mosquitto/auth/passwd
    persistence false
    log_dest stdout
    log_type all
